GET http://localhost:3001/
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3
###
GET http://localhost:3001/info
###
DELETE http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "3"
}
###
PUT http://localhost:3001/api/persons/645ac344e2a8ab9482f9d2c3
Content-Type: application/json

{
    "name": "Xi",
    "number": "222222222222222222"
}
###
###
###
GET https://phonebook-learning.fly.dev/info
###
GET https://phonebook-learning.fly.dev/api/persons
###
DELETE https://phonebook-learning.fly.dev/api/persons/3
###
POST https://phonebook-learning.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Pawelek",
    "number": "00000"
}