GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "1",
  "author": "1",
  "likes": 1,
  "url": "1"
}
###
DELETE http://localhost:3001/api/blogs/64631879c37e538fce2c84e0